FROM python:3.9-slim

WORKDIR /workspace

COPY requirements_gradio.txt /workspace/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY . /workspace

EXPOSE 7860

CMD ["python", "gradio_app.py"]