services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    ports:
      - "5000:5000"

  gradio_app:
    build:
      context: .
      dockerfile: Dockerfile-gradio
    ports:
      - "7860:7860"
    depends_on:
      - api