FROM python:3.9-slim

WORKDIR /workspace

RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    make \
    build-essential \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements_api.txt /workspace/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY . /workspace

EXPOSE 5000

CMD ["python", "app_flask.py"]