FROM python:3.9-slim

WORKDIR /workspace

RUN apt-get update && apt-get install -y \
    wget \
    unzip \
    gcc \
    g++ \
    make \
    build-essential \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements_api.txt /workspace/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY download_data.sh /workspace/download_data.sh

RUN ./download_data.sh

COPY . /workspace

RUN ./preprocessing.sh

EXPOSE 5000

CMD ["python", "app_flask.py"]